name: Create a comment on new issues

on:
  issues:
    types: [opened]
env:
   GH_TOKEN: ${{ github.token }}
   
jobs:   

  print-event:
   runs-on: ununtu-latest
   steps:
    - name: prints the event
      run: echo '${{ toJSON(github.event) }}' | jq
      shell: bash
      
  comment-with-api:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment with API
        run: |
            gh api -X POST \
              repos/${ORGANIZATION}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments \
              -f body='Me too' 
            
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZATION: ${{ github.event.user.login }}
          REPOSITORY: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
